language: node_js
sudo: false
node_js:
  - "5.9.1"

before_install:
  - npm i -g npm@3.9.0

install:
  - npm install
  - npm install grunt-cli -g

script:
  - grunt release
  - npm test
  - ./auto/bower_publish.sh
